=== codehaus/senro/branches/senro-gxt/senro-designer/schema/ComponentTemplate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://www.siveco.ro/senro/DesignerComponent"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           targetNamespace="http://www.siveco.ro/senro/DesignerComponent" elementFormDefault="qualified"
        >

    <!-- Definition of the generic types used in this schema -->

    <xs:simpleType name="positiveInteger">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="strictPositiveInteger">
        <xs:restriction base="xs:integer">
            <xs:minExclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="BasicComponentType">
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="UIComponentType">
        <xs:complexContent>
            <xs:extension base="BasicComponentType">
                <xs:attribute name="row" type="positiveInteger" default="0" use="optional"/>
                <xs:attribute name="col" type="positiveInteger" default="0"/>
                <xs:attribute name="rowSpan" type="strictPositiveInteger" default="1"/>
                <xs:attribute name="colSpan" type="strictPositiveInteger" default="1"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- Top element -->

    <xs:element name="ComponentTemplate">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Layout" maxOccurs="1"/>
                <xs:element ref="Server" maxOccurs="1"/>
                <xs:element ref="Client" maxOccurs="1"/>
                <xs:element ref="Params" maxOccurs="1"/>
                <xs:element ref="Associations" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Layout">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Grid" type="GridType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="GridType">
        <xs:complexContent>
            <xs:extension base="UIComponentType">
                <xs:sequence>
                    <xs:element ref="Columns" maxOccurs="1"/>
                    <xs:element ref="Rows" maxOccurs="1"/>
                    <xs:element name="Components">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:choice minOccurs="0" maxOccurs="unbounded">
                                    <xs:element name="Label" type="LabelType"/>
                                    <xs:element name="TextField" type="TextFieldType"/>
                                    <xs:element name="TextArea" type="TextAreaType"/>
                                    <xs:element name="Button" type="ButtonType"/>
                                    <xs:element name="CheckBox" type="CheckBoxType"/>
                                    <xs:element name="ComboBox" type="ComboBoxType"/>
                                    <xs:element name="Grid" type="GridType"/>
                                    <xs:element name="Template" type="TemplateType">
                                    </xs:element>
                                </xs:choice>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="GridSpecificationElement">
        <xs:sequence>
            <xs:element name="Alignment" minOccurs="0" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:NMTOKEN">
                        <xs:enumeration value="Left"/>
                        <xs:enumeration value="Center"/>
                        <xs:enumeration value="Right"/>
                        <xs:enumeration value="Fill"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Resize" minOccurs="0" maxOccurs="1" type="xs:decimal"/>
            <xs:element name="Size">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="Constant" type="xs:integer"/>
                        <xs:element name="Component">
                            <xs:simpleType>
                                <xs:restriction base="xs:NMTOKEN">
                                    <xs:enumeration value="Default"/>
                                    <xs:enumeration value="Pref"/>
                                    <xs:enumeration value="Min"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="Min" type="xs:integer"/>
                        <xs:element name="Max" type="xs:integer"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="Group" minOccurs="0" maxOccurs="1" type="xs:integer"/>
        </xs:sequence>

    </xs:complexType>

    <xs:element name="Columns">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Column" type="GridSpecificationElement" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Rows">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Row" type="GridSpecificationElement" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="LabelType">
        <xs:complexContent>
            <xs:extension base="UIComponentType">
                <xs:sequence>
                    <xs:element name="Text" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TextFieldType">
        <xs:complexContent>
            <xs:extension base="UIComponentType">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="TextAreaType">
        <xs:complexContent>
            <xs:extension base="UIComponentType">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ButtonType">
        <xs:complexContent>
            <xs:extension base="UIComponentType">
                <xs:sequence>
                    <xs:element name="Label" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="CheckBoxType">
        <xs:complexContent>
            <xs:extension base="UIComponentType">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ComboBoxType">
        <xs:complexContent>
            <xs:extension base="UIComponentType">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

	<xs:complexType name="TemplateType">
        <xs:complexContent>
            <xs:extension base="UIComponentType">
                <xs:sequence>
                    <xs:element name="Param">
                        <xs:complexType>
                            <xs:attribute name="name" type="xs:string"/>
                            <xs:attribute name="value" type="xs:string"/>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="Server">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="GridAllocator" type="GridAllocatorType" maxOccurs="1"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="SenroContextType">
        <xs:complexContent>
            <xs:extension base="BasicComponentType">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="GridAllocatorType">
        <xs:complexContent>
            <xs:extension base="BasicComponentType">
                <xs:attribute name="entity" type="xs:string"/>
                <xs:attribute name="columns" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="Client">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="DisplayGroup" type="DisplayGroupType" maxOccurs="1"/>
                    <xs:element name="EditingContext" type="EditingContextType" maxOccurs="1"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="DisplayGroupType">
        <xs:complexContent>
            <xs:extension base="BasicComponentType">
                <xs:sequence>
                    <xs:element name="Entity" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="EditingContextType">
        <xs:complexContent>
            <xs:extension base="BasicComponentType">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="Params">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Parameter" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Parameter">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="defaultValue" type="xs:string"/>
        </xs:complexType>

    </xs:element>

    <xs:element name="Associations">
    </xs:element>

</xs:schema>

=== codehaus/senro/senro-core/templates/list/Component.xml
<?xml version="1.0" encoding="UTF-8"?>
<ComponentTemplate xmlns="http://www.siveco.ro/senro/ComponentTemplate" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.siveco.ro/senro/ComponentTemplate file:///c:/work/SENRO_SIVECO/senro-core/src/resources/ComponentTemplate.xsd">
    <Layout>
        <Grid id="SimpleList" name="SimpleList">
            <Columns>
                <Column>
                    <Alignment>Left</Alignment>
                    <Resize>0.0</Resize>
                    <Size>
                        <Component>Default</Component>
                    </Size>
                </Column>
            </Columns>
            <Rows>
                <Row>
                    <Alignment>Center</Alignment>
                    <Resize>0.0</Resize>
                    <Size>
                        <Component>Default</Component>
                    </Size>
                </Row>
                <Row>
                    <Alignment>Center</Alignment>
                    <Resize>0.0</Resize>
                    <Size>
                        <Component>Default</Component>
                    </Size>
                </Row>
                <Row>
                    <Alignment>Center</Alignment>
                    <Resize>0.0</Resize>
                    <Size>
                        <Component>Default</Component>
                    </Size>
                </Row>
				<Row>
                    <Alignment>Center</Alignment>
                    <Resize>0.0</Resize>
                    <Size>
                        <Component>Default</Component>
                    </Size>
                </Row>
                <Row>
                    <Alignment>Center</Alignment>
                    <Resize>0.0</Resize>
                    <Size>
                        <Component>Default</Component>
                    </Size>
                </Row>
            </Rows>
            <Components>
                <Label col="0" colSpan="1" halign="Center" id="lblTitle" name="lblTitle" row="0" rowSpan="1" valign="Default">
                    <Text>@{entity.name}</Text>
                </Label>
                <List col="0" colSpan="1" entity="@{entity}" halign="Default" id="list" name="list" row="1" rowSpan="1" valign="Default"/>
                <Button col="0" colSpan="1" halign="Center" id="btnNew" name="btnNew" row="2" rowSpan="1" valign="Default">
                    <Label>New</Label>
                    <Entity>@{entity.qualifiedName}</Entity>
                    <Task>new</Task>
                    <Icon/>
                    <HoverIcon/>
                </Button>
				<TextField id="text1" name="text1" col="0" row="3" />
				<TextField id="text2" name="text2" col="0" row="4" />
            </Components>
        </Grid>
    </Layout>
    <Server/>
    <Client/>
    <Params>
        <Parameter defaultValue="@{metadata.getMetadata(senroContext.get(senroContext.MAIN_ENTITY))}" name="entity" type="org.senro.metadata.MetadataClass"/>
    </Params>
    <Associations>
		<Assoc id="assoc1" name="assoc1" type="org.senro.gwt.client.assoc.impl.TextToTextAssoc">
			<binding name="t1" value="text1">
				<aspect>text</aspect>
				<event>170</event>
			</binding>
			<binding name="t2" value="text2">
				<aspect>text</aspect>
				<event>170</event>
			</binding>
		</Assoc>
	</Associations>
</ComponentTemplate>

=== codehaus/senro/branches/senro-gxt/senro-designer/schema/SimpleList.xml
<?xml version="1.0"?>
<ComponentTemplate xmlns="http://www.siveco.ro/senro/ComponentTemplate" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.siveco.ro/senro/ComponentTemplate ComponentTemplate.xsd">
	<Layout>
		<Grid id="grid1" name="grid1">
			<Columns>
				<Column>
					<Alignment>Right</Alignment>
				</Column>
			</Columns>

			<Rows>
				<Row>
					<Alignment>Middle</Alignment>
				</Row>
				<Row>
					<Alignment>Middle</Alignment>
				</Row>
			</Rows>

			<Components>
				<List id="list" name="list" entity="@{entity}" row="0" col="0" />
				<Button id="btnNew" name="btnNew" row="1" col="0">
					<Label>New</Label>
					<Entity>@{entity.qualifiedName}</Entity>
					<Task>new</Task>
				</Button>
			</Components>
		</Grid>
	</Layout>

	<Server>
	</Server>
	
	<Client>
	</Client>

	<Params>
		<Parameter name="entity" type="org.senro.metadata.MetadataClass"/>
	</Params>

	<Associations/>
</ComponentTemplate>

=== codehaus/senro/branches/senro-gxt/senro-designer/schema/Selector.xml
<?xml version="1.0"?>
<ComponentTemplate xmlns="http://www.siveco.ro/senro/ComponentTemplate" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.siveco.ro/senro/ComponentTemplate ComponentTemplate.xsd">
	<Layout>
		<Grid id="grid1" name="grid1">
			<Columns>
				<Column>
					<Alignment>Left</Alignment>
				</Column>
			</Columns>

			<Rows>
				<Row>
					<Alignment>Middle</Alignment>
				</Row>
				<Row>
					<Alignment>Middle</Alignment>
				</Row>
			</Rows>

			<Components>
				<List id="list" name="list" entity="@{entity}" row="0" col="0" />
				<Button id="btnSelect" name="btnSelect" row="1" col="0" halign="Center">
					<Label>Select</Label>
					<Entity>@{entity.qualifiedName}</Entity>
					<Task>select</Task>
				</Button>
			</Components>
		</Grid>
	</Layout>

	<Server>
	</Server>
	
	<Client>
	</Client>

	<Params>
		<Parameter name="entity" type="org.senro.metadata.MetadataClass" defaultValue="@{metadata.getMetadata(senroContext.get(senroContext.MAIN_ENTITY))}" />
	</Params>

	<Associations/>
</ComponentTemplate>

=== codehaus/senro/branches/senro-gxt/senro-designer/schema/MainPage.xml
<?xml version="1.0"?>
<ComponentTemplate xmlns="http://www.siveco.ro/senro/ComponentTemplate" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.siveco.ro/senro/ComponentTemplate ComponentTemplate.xsd">
	<Layout>
		<Grid id="grid1" name="grid1">
			<Columns>
				<Column>
					<Alignment>Left</Alignment>
				</Column>
				<Column>
					<Alignment>Center</Alignment>
				</Column>
			</Columns>
			<Rows>
				<Row>
					<Alignment>Top</Alignment>
				</Row>
			</Rows>
			<Components>
				<Tree id="tree1" name="menu" row="0" col="0">
					<Iterator id="iter1" name="menuIterator" list="@{metadata.allEntities.values()}">
						<TreeNode>
							<Text>@{menuIterator.currentItem.qualifiedName}</Text>
						</TreeNode>
					</Iterator>
				</Tree>
				<RootPanel id="rootPanel" name="rootPanel" row="0" col="1" />
			</Components>
		</Grid>
	</Layout>

	<Server/>
	<Client/>

	<Params>
	</Params>

	<Associations/>
</ComponentTemplate>

=== codehaus/senro/branches/senro-gxt/senro-core/src/resources/SimpleForm.xml
<?xml version="1.0"?>
<ComponentTemplate xmlns="http://www.siveco.ro/senro/DesignerComponent" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.siveco.ro/senro/DesignerComponent ComponentTemplate.xsd">
	<Layout>
		<Grid id="grid1" name="grid1">
			<Columns>
				<Column>
					<Alignment>Right</Alignment>
				</Column>
				<Column>
					<Alignment>Left</Alignment>
				</Column>
				<Column>
					<Alignment>Right</Alignment>
				</Column>
				<Column>
					<Alignment>Left</Alignment>
				</Column>
			</Columns>

			<Rows>
				<Row>
					<Alignment>Center</Alignment>
				</Row>
				<Row>
					<Alignment>Center</Alignment>
				</Row>
				<Row>
					<Alignment>Center</Alignment>
				</Row>
				<Row>
					<Alignment>Center</Alignment>
				</Row>
				<Row>
					<Alignment>Center</Alignment>
				</Row>
				<Row>
					<Alignment>Center</Alignment>
				</Row>
			</Rows>

			<Components>
				<!-- Row 1-->
				<Label id="label1" name="lblTitle1" row="1" col="2" colSpan="2">
					<Text>Currency</Text>
				</Label>

				<!-- Row 2-->
				<Label id="label2" name="lblCode" row="2" col="1">
					<Text>Code:</Text>
				</Label>
				<TextField id="textfield1" name="txtCode" row="2" col="2"/>
				<Label id="label3" name="lblValid" row="2" col="3">
					<Text>Valid:</Text>
				</Label>
				<CheckBox id="checkbox1" name="cbValid1" row="2" col="4"/>
				
				<!-- Row 3-->
				<Label id="label4" name="lblName" row="3" col="1">
					<Text>Name:</Text>
				</Label>
				<TextField id="textfield2" name="txtName" row="3" col="2"/>
				<Label id="label5" name="lblType" row="3" col="3">
					<Text>Type:</Text>
				</Label>
				<ComboBox id="combobox1" name="cbType" row="3" col="4"/>

				<!-- Row 4-->
				<Label id="label6" name="lblDate" row="4" col="1">
					<Text>Date:</Text>
				</Label>
				<DateField id="datefield1" name="dtDate" row="4" col="2"/>

				<!-- Row 5-->
				<Button id="button1" name="btnSave" row="5" col="1" colSpan="2">
					<Label>Save</Label>
				</Button>
				<Button id="button2" name="btnBack" row="5" col="3" colSpan="2">
					<Label>Back</Label>
				</Button>

				<Grid id="grid2" name="grid2" row="6" col="1" colSpan="4">
					<Columns>
						<Column>
							<Alignment>Right</Alignment>
						</Column>
						<Column>
							<Alignment>Left</Alignment>
						</Column>
						<Column>
							<Alignment>Right</Alignment>
						</Column>
						<Column>
							<Alignment>Left</Alignment>
						</Column>
					</Columns>
				
					<Rows>
						<Row>
							<Alignment>Center</Alignment>
						</Row>
						<Row>
							<Alignment>Center</Alignment>
						</Row>
						<Row>
							<Alignment>Center</Alignment>
						</Row>
						<Row>
							<Alignment>Center</Alignment>
						</Row>
						<Row>
							<Alignment>Center</Alignment>
						</Row>
					</Rows>

					<Components>
						<!-- Row 1-->
						<Label id="label7" name="lblTitle2" row="1" col="2" colSpan="2">
							<Text>Currency2</Text>
						</Label>

						<!-- Row 2-->
						<Label id="label8" name="lblCode2" row="2" col="1">
							<Text>Code2:</Text>
						</Label>
						<TextField id="textfield3" name="txtCode2" row="2" col="2"/>
						<Label id="label9" name="lblValid2" row="2" col="3">
							<Text>Valid2:</Text>
						</Label>
						<CheckBox id="checkbox2" name="cbValid2" row="2" col="4"/>
				
						<!-- Row 3-->
						<Label id="label10" name="lblName2" row="3" col="1">
							<Text>Name2:</Text>
						</Label>
						<TextField id="textfield4" name="txtName2" row="3" col="2"/>
						<Label id="label11" name="lblType2" row="3" col="3">
							<Text>Type2:</Text>
						</Label>
						<ComboBox id="combobox2" name="cbType2" row="3" col="4"/>

						<!-- Row 4-->
						<Label id="label12" name="lblDate2" row="4" col="1">
							<Text>Date2:</Text>
						</Label>
						<DateField id="datefield2" name="dtDate2" row="4" col="2"/>

						<!-- Row 5-->
						<Button id="button3" name="btnSave2" row="5" col="1" colSpan="2">
							<Label>Save2</Label>
						</Button>
						<Button id="button4" name="btnBack2" row="5" col="3" colSpan="2">
							<Label>Back2</Label>
						</Button>
					</Components>
				</Grid>
			</Components>
		</Grid>
	</Layout>

	<Server>
		<GridAllocator id="gridAllocator1" name="gridAllocator" columns="4" entity="$entity"/>
	</Server>
	
	<Client>
	</Client>

	<Params>
		<Parameter name="entity" type="java.lang.Class" defaultValue="$senroContext.mainEntity"/>
	</Params>

	<Associations/>
</ComponentTemplate>

=== codehaus/senro/senro-designer/schema/SimpleForm.xml
<?xml version="1.0"?>
<ComponentTemplate xmlns="http://www.siveco.ro/senro/DesignerComponent" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.siveco.ro/senro/DesignerComponent ComponentTemplate.xsd">
	<Layout>
		<Grid id="grid1" name="grid1">
			<Columns>
				<Column>
					<Alignment>Left</Alignment>
				</Column>
				<Column>
					<Alignment>Left</Alignment>
				</Column>
			</Columns>

			<Rows>
				<Row>
					<Alignment>Middle</Alignment>
				</Row>
				<Row>
					<Alignment>Middle</Alignment>
				</Row>
				<Row>
					<Alignment>Middle</Alignment>
				</Row>
			</Rows>

			<Components>
				<GridAllocatorRenderer id="gridRenderer" name="gridRenderer" gridAllocator="@{gridAllocator}" row="0" col="0" colSpan="2" />
				<Button id="btnBack" name="btnBack" row="1" col="0">
					<Label>Back</Label>
				</Button>
				<Button id="btnSave" name="btnSave" row="1" col="1">
					<Label>Save</Label>
				</Button>
				<TabPanel id="tabPanel" name="tabPanel" row="2" col="0" colSpan="2">
					<Iterator id="tabIter" name="tabIter" list="@{entity.properties}">
						<Conditional>
							<If condition="@{tabIter.currentItem.isMany}">
								<TabPage title="@{tabIter.currentItem.type}">
									<Template file="SimpleList.xml">
										<Param name="entity" value="@{metadataManager.getMetadata(tabIter.currentItem.type)}" />
									</Template>
								</TabPage>
							</If>
						</Conditional>
					</Iterator>
				</TabPanel>
			</Components>
		</Grid>
	</Layout>

	<Server>
		<GridAllocator id="gridAllocator1" name="gridAllocator" columns="4" entity="@{entity}"/>
	</Server>
	
	<Client>
	</Client>

	<Params>
		<Parameter name="entity" type="org.senro.metadata.MetadataClass"/>
		<Parameter name="metadataManager" type="org.senro.metadata.MetadataManager"/>
	</Params>

	<Associations/>
</ComponentTemplate>

=== codehaus/senro/senro-core/src/resources/MainPage.xml
<?xml version="1.0"?>
<ComponentTemplate xmlns="http://www.siveco.ro/senro/DesignerComponent" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.siveco.ro/senro/DesignerComponent ComponentTemplate.xsd">
	<Layout>
		<Grid id="grid1" name="grid1">
			<Columns>
				<Column>
					<Alignment>Left</Alignment>
				</Column>
				<Column>
					<Alignment>Center</Alignment>
				</Column>
			</Columns>
			<Rows>
				<Row>
					<Alignment>Center</Alignment>
				</Row>
				<Row>
					<Alignment>Center</Alignment>
				</Row>
			</Rows>
			<Components>
				<Tree id="tree1" name="menu" row="1" col="1">
				    <TreeNode>
						<Label id="lbl123" name="lbl123">
							<Text>1234</Text>
						</Label>
					</TreeNode>
					<Iterator id="iter1" name="menuIterator" list="@{allEntities}">
						<TreeNode>
							<Label>
								<Text>@{menuIterator.currentItem.metadata.name}</Text>
							</Label>
						</TreeNode>
					</Iterator>
				</Tree>
				<RootPanel id="rootPanel" name="rootPanel" row="1" col="2" />
				<Label id="label1" name="label1" row="2" col="1">
					<Text>Hello world</Text>
				</Label>
				<Label id="label2" name="label2" row="2" col="1">
					<Text>Mesajul de la label1 este: @{label1.text}</Text>
				</Label>
			</Components>
		</Grid>
	</Layout>

	<Server/>
	<Client/>

	<Params>
		<Parameter name="allEntities" type="java.util.List"/>
	</Params>

	<Associations/>
</ComponentTemplate>

=== codehaus/senro/senro-core/templates/PopupSelector.xml
<?xml version="1.0"?>
<ComponentTemplate xmlns="http://www.siveco.ro/senro/ComponentTemplate" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.siveco.ro/senro/ComponentTemplate ComponentTemplate.xsd">
	<Layout>
		<Grid id="grid1" name="grid1">
			<Columns>
				<Column>
					<Alignment>Left</Alignment>
				</Column>
				<Column>
					<Alignment>Left</Alignment>
				</Column>
			</Columns>

			<Rows>
				<Row>
					<Alignment>Middle</Alignment>
				</Row>
			</Rows>

			<Components>
				<Iterator id="iter" name="iter" list="@{ukFields}">
					<SwitchComponent property="@{iter.currentItem}" row="0" col="@{iter.currentIndex}" createLabel="false" />
				</Iterator>
				<Button id="btnSel" name="btnSel" row="0" col="@{iter.currentIndex}" type="icon">
					<Icon>icons/fold_off.gif</Icon>
					<HoverIcon>icons/fold_on.gif</HoverIcon>
					<Entity>@{entity.qualifiedName}</Entity>
				</Button>
			</Components>
		</Grid>
		<Popup id="@{entity.qualifiedName}" name="@{entity.qualifiedName}">
			<Columns>
				<Column>
					<Alignment>Center</Alignment>
				</Column>
			</Columns>

			<Rows>
				<Row>
					<Alignment>Middle</Alignment>
				</Row>
				<Row>
					<Alignment>Middle</Alignment>
				</Row>
			</Rows>

			<Components>
				<List id="list" name="list" entity="@{entity}" row="0" col="0" />
				<Button id="btnSelect" name="btnSelect" row="1" col="0" halign="Center">
					<Label>Select</Label>
					<Entity>@{entity.qualifiedName}</Entity>
					<Task>select</Task>
				</Button>
			</Components>
		</Popup>
	</Layout>

	<Server>
	</Server>
	
	<Client>
	</Client>

	<Params>
		<Parameter name="entity" type="org.senro.metadata.MetadataClass" defaultValue="@{metadata.getMetadata(senroContext.get(senroContext.MAIN_ENTITY))}" />
		<Parameter name="ukFields" type="java.util.List" defaultValue="@{metadata.getMetadata(senroContext.get(senroContext.MAIN_ENTITY)).getUKFields()}" />
	</Params>

	<Associations/>
</ComponentTemplate>
